In [ ]:
import pandas as pd

Data from NIH data

https://grant-witness.us/nih-data.html

https://hsph.harvard.edu/news/creating-a-trusted-database-of-federal-research-funding-cuts/

In [ ]:
df = pd.read_csv('/content/nih_v3_terminations.csv')

In [ ]:
df

,grant_id,subgrant_id,core_award_number,full_award_number,activity_code,institute_code,subproject_id,current_status,detailed_status,title,...,opportunity_title,opportunity_url,current_total_obligated,post_termination_deobligation,award_value,award_outlaid,award_remaining,reporter_url,usaspending_url,taggs_url
0,AA007459,NaN,T32AA007459,5T32AA007459-40,T32,AA,NaN,Restored,Unfrozen (confirmed),Alcohol Intervention Treatment Outcome Researc...,...,Ruth L. Kirschstein National Research Service ...,https://grants.nih.gov/grants/guide/pa-files/P...,8903933.00,NaN,8903933.00,2021558.65,6882374.35,https://reporter.nih.gov/project-details/11098673,https://www.usaspending.gov/award/ASST_NON_T32...,NaN
1,AA019072,NaN,P01AA019072,5P01AA019072-15,P01,AA,NaN,Restored,Unfrozen (confirmed),Addressing alcohol misuse in HIV prevention an...,...,Alcohol-HIV/AIDS Program Project (P01 Clinical...,https://grants.nih.gov/grants/guide/pa-files/R...,19658333.00,NaN,19658333.00,4853500.60,14804832.40,https://reporter.nih.gov/project-details/10879090,https://www.usaspending.gov/award/ASST_NON_P01...,NaN
2,AA024434,NaN,R01AA024434,5R01AA024434-10,R01,AA,NaN,Restored,Unfrozen (confirmed),Notch-dependent microcircuit regulation of alc...,...,Research Project Grant (Parent R01 Clinical Tr...,https://grants.nih.gov/grants/guide/pa-files/P...,3903456.00,NaN,3903456.00,1545133.43,2358322.57,https://reporter.nih.gov/project-details/11137591,https://www.usaspending.gov/award/ASST_NON_R01...,NaN
3,AA026186,NaN,R01AA026186,5R01AA026186-10,R01,AA,NaN,Restored,Unfrozen (confirmed),Endocannabinoid Mechanisms in the Pathophysiol...,...,NIH Research Project Grant (Parent R01 Clinica...,https://grants.nih.gov/grants/guide/pa-files/P...,3188075.26,NaN,3188075.26,1317401.98,1870673.28,https://reporter.nih.gov/project-details/11324549,https://www.usaspending.gov/award/ASST_NON_R01...,NaN
4,AA026297,NaN,R01AA026297,5R01AA026297-09,R01,AA,NaN,Restored,Unfrozen (confirmed),Aldh2 and epithelial homeostasis and pathobiology,...,NIH Research Project Grant (Parent R01 Clinica...,https://grants.nih.gov/grants/guide/pa-files/P...,2928362.18,NaN,2928362.18,1226006.45,1702355.73,https://reporter.nih.gov/project-details/11381708,https://www.usaspending.gov/award/ASST_NON_R01...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5516,TW012677,NaN,R01TW012677,1R01TW012677-01A1,R01,TW,NaN,Restored,Unfrozen (confirmed),Engaging Vulnerable Women in HIV Prevention an...,...,Interventions for Stigma Reduction to Improve ...,https://grants.nih.gov/grants/guide/pa-files/P...,173197.00,NaN,173197.00,169209.31,3987.69,https://reporter.nih.gov/project-details/11002762,https://www.usaspending.gov/award/ASST_NON_R01...,NaN
5517,TW012808,NaN,P20TW012808,5P20TW012808-02,P20,TW,NaN,Restored,Reinstated (confirmed),The Anga Center for Community Health and Well-...,...,Exploratory Grants for Climate Change and Heal...,https://grants.nih.gov/grants/guide/pa-files/R...,2109010.00,NaN,2109010.00,60720.12,2048289.88,https://reporter.nih.gov/project-details/11397208,https://www.usaspending.gov/award/ASST_NON_P20...,NaN
5518,TW012850,NaN,K43TW012850,5K43TW012850-02,K43,TW,NaN,Restored,Reinstated (unconfirmed),Adapting an evidence-based intervention to imp...,...,Emerging Global Leader Award (K43 Independent ...,https://grants.nih.gov/grants/guide/pa-files/P...,134406.00,NaN,134406.00,66427.00,67979.00,https://reporter.nih.gov/project-details/11374076,https://www.usaspending.gov/award/ASST_NON_K43...,NaN
5519,TW012904,NaN,R01TW012904,5R01TW012904-02,R01,TW,NaN,Restored,Reinstated (confirmed),Kabawil: Adapting an Intervention to Reduce In...,...,Interventions for Stigma Reduction to Improve ...,https://grants.nih.gov/grants/guide/pa-files/P...,432176.00,NaN,432176.00,220077.98,212098.02,https://reporter.nih.gov/project-details/11362792,https://www.usaspending.gov/award/ASST_NON_R01...,NaN
5520,TW013028,NaN,P20TW013028,5P20TW013028-02,P20,TW,NaN,Restored,Reinstated (confirmed),Center for Effective and Accessible Research-b...,...,Exploratory Grants for Climate Change and Heal...,https://grants.nih.gov/grants/guide/pa-files/R...,2525164.00,NaN,2525164.00,845984.22,1679179.78,https://reporter.nih.gov/project-details/11193870,https://www.usaspending.gov/award/ASST_NON_P20...,NaN

In [ ]:
df.columns

Index(['grant_id', 'subgrant_id', 'core_award_number', 'full_award_number',
       'activity_code', 'institute_code', 'subproject_id', 'current_status',
       'detailed_status', 'title', 'latest_disruption_date',
       'latest_restoration_date', 'first_termination_date',
       'latest_termination_date', 'first_reinstatement_date',
       'latest_reinstatement_date', 'frozen_date', 'unfrozen_date',
       'latest_outlay', 'latest_renewal', 'latest_budget_end', 'project_start',
       'project_end', 'event_history', 'signals', 'has_been_terminated',
       'has_been_reinstated', 'has_been_frozen', 'has_been_unfrozen',
       'has_been_delayed', 'study_section', 'abstract',
       'public_health_relevance', 'terms', 'spending_categories',
       'categories_predicted', 'funding_category', 'program_office',
       'nih_activity', 'flagged_words', 'org_name', 'org_state', 'org_city',
       'org_country', 'org_type', 'org_traits', 'pct_ugrad_pellgrant',
       'pct_ugrad_fedloan', 'department_type', 'congressional_district',
       'cfda_number', 'cfda_title', 'opportunity_number', 'opportunity_title',
       'opportunity_url', 'current_total_obligated',
       'post_termination_deobligation', 'award_value', 'award_outlaid',
       'award_remaining', 'reporter_url', 'usaspending_url', 'taggs_url'],
      dtype='object')

In [ ]:
df['flagged_words']

0                                                     NaN
1       diverse, men who have sex with men, msm, sex, ...
2                bias, biased, diverse, expression, trans
3                                                   trans
4                                       expression, trans
                              ...
5516    advocacy, at risk, barrier, barriers, gender, ...
5517                                at risk, trans, women
5518                               barrier, barriers, sex
5519    barrier, barriers, discrimination, diverse, in...
5520                                    accessible, trans
Name: flagged_words, Length: 5521, dtype: object

From https://pen.org/banned-words-list/

In [ ]:
# banned_words = """abortion accessibility Accessible activism activists advocacy advocate advocates affirmative action affirmative action programs affirming care affordable home affordable housing agricultural water agrivoltaics air pollution all-inclusive allyship alternative energy anti-racism antiracist asexual assigned at birth assigned female at birth assigned male at birth at risk autism aviation fuel barrier barriers belong bias biased Biased toward biases Biases towards bioenergy biofuel biogas biologically female biologically male biomethane bipoc bisexual Black black and latinx breastfeed + people breastfeed + person Cancer Moonshot carbon emissions mitigation carbon footprint carbon markets carbon pricing carbon sequestration CEC changing climate chestfeed + people chestfeed + person clean energy clean fuel clean power clean water climate climate accountability climate change climate consulting climate crisis climate model climate models climate resilience climate risk climate science climate smart agriculture climate smart forestry climate variability climate-change climatesmart commercial sex worker community community diversity community equity confirmation bias contaminants of environmental concern continuum Covid-19 critical race theory cultural competence cultural differences cultural heritage Cultural relevance cultural sensitivity culturally appropriate culturally responsive decarbonization definition DEI DEIA DEIAB DEIJ diesel dietary guidelines/ultraprocessed foods dirty energy disabilities disability disabled disadvantaged discriminated discrimination discriminatory discussion of federal policies disparity diverse diverse backgrounds diverse communities diverse community diverse group diverse groups diversified diversify diversifying diversity diversity and inclusion diversity in the workplace diversity, equity, and inclusion diversity/equity efforts EEJ EJ elderly electric vehicle emissions energy conversion energy transition enhance the diversity enhancing diversity entitlement environmental justice environmental quality equal opportunity equality equitable equitableness equity ethnicity evidence-based excluded exclusion expression female females feminism fetus field drainage fluoride fostering inclusivity fuel cell gay GBV gender gender based gender based violence gender diversity gender dysphoria gender expression gender identity gender ideology gender nonconformity gender transition gender-affirming care gendered genders geothermal GHG emission GHG modeling GHG monitoring global warming green green infrastructure greenhouse gas emission groundwater pollution Gulf of Mexico H5N1/bird flu hate hate speech health disparity health equity hispanic hispanic minority historically housing affordability housing efficiency hydrogen vehicle identity ideology immigrants implicit bias implicit biases inclusion inclusive inclusive leadership inclusiveness inclusivity Increase diversity increase the diversity indigenous indigenous community/ people inequalities inequality inequitable inequities injustice institutional integration intersectional intersectionality intersex issues concerning pending legislation justice40 key groups key people key populations Latinx lesbian lgbt LGBTQ low-emission vehicle low-income housing male dominated marginalize marginalized marijuana measles membrane filtration men who have sex with men mental health methane emissions microplastics migrant minorities minority minority serving institution most risk MSI msm multicultural Mx Native American NCI budget net-zero non-binary nonbinary noncitizen non-conforming nonpoint source pollution nuclear energy nuclear power obesity opioids oppression oppressive orientation pansexual PCB peanut allergies people + uterus people of color people-centered care person-centered person-centered care PFAS PFOA photovoltaic polarization political pollution pollution abatement pollution remediation prefabricated housing pregnant people pregnant person pregnant persons prejudice privilege privileges promote promote diversity promoting diversity pronoun pronouns prostitute pyrolysis QT queer race race and ethnicity racial racial diversity racial identity racial inequality racial justice racially racism runoff rural water safe drinking water science-based sediment remediation segregation self-assessed sense of belonging sex sexual preferences sexuality social justice social vulnerability socio cultural socio economic sociocultural socioeconomic status soil pollution solar energy solar power special populations stem cell or fetal tissue research stereotype stereotypes subsidized housing sustainability/sustainable sustainable construction systemic systemically tax breaks tax credits tax subsidies they/them tile drainage topics of federal investigations topics that have received recent attention from Congress topics that have received widespread or critical media attention trans transexual transexualism transexuals transgender transgender military personnel transgender people transitional housing trauma traumatic tribal two-spirit unconscious bias under appreciated under represented under served underprivileged underrepresentation underrepresented underserved understudied undervalued vaccines victim victims vulnerable vulnerable populations water collection water conservation water distribution water efficiency water management water pollution water quality water storage water treatment white privilege wind power woman women women and underrepresented women in leadership""".split()

From Sen. Cruz's list (official)

In [ ]:

statusbanstring = '''
ACTIVISM; ACTIVIST; ACTIVISTS; ADVOCACY; ADVOCATE; ADVOCATES; AFFIRMATIVE ACTION; BIAS TOWARD;
BIAS TOWARDS; BIASED; BIASED TOWARD; BIASED TOWARDS; BIASES; BIASES TOWARD; BIASES TOWARDS; DE
COLONIZATION; DE COLONIZE; DE COLONIZED; DE COLONIZING; DE SEGREGATE; DE SEGREGATED; DE
SEGREGATES; DE SEGREGATION; DECOLONIZATION; DECOLONIZE; DECOLONIZED; DECOLONIZING;
DESEGREGATE; DESEGREGATED; DESEGREGATES; DESEGREGATION; DISCRIMINATE; DISCRIMINATED;
DISCRIMINATION; DISCRIMINATORY; DIVISIVENESS; EXCLUDED; EXCLUSION; EXCLUSIVE; FEEL SEEN AND HEARD;
HATE SPEECH; HISTORICALLY; IMPLICIT BIAS; IMPLICIT BIASES; INJUSTICE; INJUSTICES; INSTITUTIONAL;
INSTITUTIONALIZE; INSTITUTIONALIZED; INSTITUTIONALLY; INTERGENERATIONAL TRAUMA; INTERSECTIONAL;
INTERSECTIONALITY; MARGINALIZATION; MARGINALIZE; MARGINALIZED; MICRO AGGRESSION; MICRO
AGGRESSIONS; MICRO AGGRESSIVE; MICRO AGGRESSIVENESS; MICROAGGRESSION; MICROAGGRESSIONS;
MICROAGGRESSIVE; MICROAGGRESSIVENESS; MINORITIES; MINORITY; OPPRESSED; OPPRESSIVE;
OPPRESSIVENESS; OPPRESSION; POLARIZATION; POLARIZE; POLITICIZATION; POLITICIZE; POLITICAL; PREJUDICE;
PREJUDICES; PRIVILEGE; PRIVILEGED; PRIVILEGES; REPARATION; REPARATIONS; SEGREGATED; SEGREGATION;
SOCIO ECONOMIC; SOCIOECONOMIC; STATUS; STATUSES; STEREOTYPE; STEREOTYPES; STEREOTYPICAL;
STEREOTYPING; SYSTEM OF OPPRESSION; SYSTEMATIC OPPRESSION; SYSTEMATICALLY OPPRESSED; SYSTEMIC;
SYSTEMIC OPPRESSION; SYSTEMICAL; SYSTEMICALLY; SYSTEMICALLY OPPRESSED; SYSTEMS OF OPPRESSION;
SYSTEMS OF POWER; TRAUMA; TRAUMATIC; UNDER APPRECIATED; UNDER APPRECIATION; UNDER PRIVILEGE;
UNDER PRIVILEGED; UNDER REPRESENTATION; UNDER REPRESENTED; UNDER SERVED; UNDER SERVING; UNDER
VALUED; UNDER VALUING; UNDERAPPRECIATED; UNDERAPPRECIATION; UNDERPRIVILEGE; UNDERPRIVILEGED;
UNDERREPRESENTATION; UNDERREPRESENTED; UNDERSERVED; UNDERSERVING; UNDERVALUED; UNDERVALUING;
UNJUST; VICTIM; VICTIMHOOD; VICTIMIZED; VICTIMS; VOICES ARE ACKNOWLEDGED; VOICES HEARD; VOICES
MATTER; UNEQUAL OPPORTUNITIES; UNEQUAL OPPORTUNITY; SAFE SPACE; SAFE SPACES; SENSE OF
BELONGING; SENSE OF BELONGINGNESS; WELCOMING ENVIRONMENT; BARRIER; BARRIERS; DISABILITIES;
DISABILITY; ALLY; ALLYSHIP.
'''

socialbanstring = '''
ADVANCE DIVERSITY; ADVANCE INCLUSIVITY; ADVANCE THE DIVERSITY; ADVANCING DIVERSITY; ADVANCING
INCLUSIVE; ALLIANCE FOR DIVERSITY; BACKGROUND INCLUSIVITY; BI CULTURAL; BICULTURAL; BLACK CULTURAL;
BLACK CULTURE; BLACK CULTURES; BROADEN DIVERSITY; BROADEN THE DIVERSITY; COMMITMENT TO DIVERSITY;
COMMUNITY DIVERSITY; COMMUNITY EQUITY; COMMUNITY INCLUSIVITY; CULTURAL ACTIVISM; CULTURAL
ACTIVIST; CULTURAL ACTIVISTS; CULTURAL ADVOCACY; CULTURAL ADVOCATE; CULTURAL AND ETHNIC;
CULTURAL AND RACIAL; CULTURAL APPROPRIATION; CULTURAL APPROPRIATIONS; CULTURAL BIAS; CULTURAL
COMPETENCY; CULTURAL CONNECTIONS; CULTURAL DIFFERENCES; CULTURAL HERITAGE; CULTURAL HUMILITY;
CULTURAL INEQUALITIES; CULTURAL INEQUALITY; CULTURAL INEQUITIES; CULTURAL INEQUITY; CULTURAL
INJUSTICE; CULTURAL INJUSTICES; CULTURAL JUSTICE; CULTURAL RELEVANCE; CULTURAL SEGREGATION;
CULTURALLY ATTUNED; CULTURALLY BIASED; CULTURALLY RESPONSIVE; CULTURALLY SENSITIVE; CULTURALLY
SUSTAINABLE; CULTURALLY SUSTAINING; CULTURE AND ETHNICITY; CULTURE AND RACE; CULTURES AND
ETHNICITIES; CULTURES AND RACES; DEI; DEIJ; DIVERSE BACKGROUND; DIVERSE BACKGROUNDS; DIVERSE
COMMUNITIES; DIVERSE COMMUNITY; DIVERSE GROUP; DIVERSE GROUPS; DIVERSE INDIVIDUAL; DIVERSE
INDIVIDUALS; DIVERSE STATUS; DIVERSE STATUSES; DIVERSE VOICES; DIVERSIFIED; DIVERSIFY; DIVERSIFYING;
DIVERSITY AND EQUITY; DIVERSITY AND INCLUSION; DIVERSITY AND INCLUSIVITY; DIVERSITY AWARENESS;
DIVERSITY EQUITY; EMPHASIS ON DIVERSITY; EMPHASIZE DIVERSITY; EMPHASIZING DIVERSITY; ENCOURAGE
DIVERSITY; ENCOURAGING DIVERSITY; ENHANCE DIVERSITY; ENHANCE THE DIVERSITY; ENHANCING DIVERSITY;
EQUAL OPPORTUNITIES; EQUAL OPPORTUNITY; EQUALITIES; EQUALITY; EQUITABLE; EQUITABLE AND INCLUSIVE;
EQUITIES; EQUITY; ETHNIC AND CULTURAL; ETHNIC CULTURAL; ETHNIC CULTURE; ETHNIC CULTURES; ETHNIC
DIVERSITY; ETHNIC EQUITY; ETHNICITIES AND CULTURES; ETHNICITY AND CULTURE; FOSTER DIVERSITY;
FOSTERING DIVERSITY; FOSTERING INCLUSIVE; FOSTERING INCLUSIVITY; FOSTERING THE DIVERSITY; GROUP
EQUITY; GROUP INCLUSIVITY; HISPANIC CULTURAL; HISPANIC CULTURE; HISPANIC CULTURES; INCLUSION;
INCLUSIVE; INCLUSIVE LANGUAGE; INCLUSIVENESS; INCLUSIVITY; INCLUSIVITY AND DIVERSITY; INCREASE DIVERSITY;
INCREASE THE DIVERSITY; INCREASES DIVERSITY; INCREASES THE DIVERSITY; INCREASING DIVERSITY; INCREASING
THE DIVERSITY; INDIGENOUS CULTURAL; INDIGENOUS CULTURE; INDIGENOUS CULTURES; INEQUALITIES;
INEQUALITY; INEQUITABLE; INEQUITIES; INEQUITY; INTER CULTURAL; INTER CULTURALLY; INTERCULTURAL;
INTERCULTURALLY; LACK OF DIVERSITY; LATINX CULTURAL; LATINX CULTURE; LATINX CULTURES; MULTI CULTURAL;
MULTI CULTURALLY; MULTICULTURAL; MULTICULTURALLY; PROMOTE DIVERSITY; PROMOTING DIVERSITY;
SEGREGATED CULTURES; SOCIAL ACTIVISM; SOCIAL ACTIVIST; SOCIAL ACTIVISTS; SOCIAL ADVOCACY; SOCIAL
ADVOCATE; SOCIAL BIAS; SOCIAL BIASES; SOCIAL INEQUALITIES; SOCIAL INEQUALITY; SOCIAL INEQUITIES;
SOCIAL INEQUITY; SOCIAL INJUSTICE; SOCIAL INJUSTICES; SOCIAL JUSTICE; SOCIAL JUSTICE ACTIVISM; SOCIAL
JUSTICE ADVOCACY; SOCIAL JUSTICE ADVOCATE; SOCIALLY BIASED; SOCIO CULTURAL; SOCIO CULTURALLY;
SOCIOCULTURAL; SOCIOCULTURALLY; STRUCTURAL INEQUALITY; STRUCTURAL INEQUITY; SUPPORT DIVERSITY;
SUPPORTING DIVERSITY; TRANS CULTURAL; TRANSCULTURAL; SOCIALLY RELEVANT; CULTURALLY RELEVANT
'''

genderbanstring='''
BIGOT; BIGOTRY; BLACK FEMALE; BLACK FEMALES; BLACK MALE; BLACK MALES; BLACK MEN; BLACK WOMEN;
CISGENDER; CISNORMATIVE; CISNORMATIVITY; COLORED FEMALE; COLORED FEMALES; COLORED MALE;
COLORED MALES; COLORED MEN; COLORED WOMEN; FEMALE; FEMALE VOICES; FEMALES; FEMININITY;
FEMINISM; FEMINIST; FEMINISTIC; FLUID IDENTITY; GENDER; GENDER ACCEPTANCE; GENDER AFFIRMATION;
GENDER AFFIRMING; GENDER AND SEXUAL; GENDER APPRECIATION; GENDER BASED; GENDER BINARY; GENDER
DISCRIMINATION; GENDER DISPARITIES; GENDER DISPARITY; GENDER DIVERSITY; GENDER DYSMORPHIA; GENDER
DYSPHORIA; GENDER FLUID; GENDER FLUIDITY; GENDER IDENTITY; GENDER IDEOLOGY; GENDER INCLUSIVE;
GENDER INCLUSIVITY; GENDER MARGINALIZED; GENDER MINORITIES; GENDER MINORITY; GENDER NEURAL;
GENDER NON BINARY; GENDER NON CONFORMING; GENDER NONBINARY; GENDER NONCONFORMING;
GENDER OPPRESSION; GENDER PREFERENCE; GENDER PREFERENCES; GENDER SPECTRUM; GENDER
STEREOTYPES; GENDER TRANSITION; GENDER TRANSITIONING; GENDER TYPICAL; GENDERS; HETEROSEXUAL;
HISPANIC FEMALE; HISPANIC FEMALES; HISPANIC MALE; HISPANIC MALES; HISPANIC MEN; HISPANIC WOMEN;
HISTORICALLY MALE; INDIGENOUS FEMALE; INDIGENOUS FEMALES; INDIGENOUS MALE; INDIGENOUS MALES;
INDIGENOUS MEN; INDIGENOUS WOMEN; INTERSECTIONAL FEMINISM; LATINA FEMALE; LATINA FEMALES; LATINA
MALE; LATINA MALES; LATINA MEN; LATINA WOMEN; LATINX FEMALE; LATINX FEMALES; LATINX MALE; LATINX
MALES; LATINX MEN; LATINX WOMEN; LGBT; LGBTQ; LGBTQ+; LGBTQIA; MALE DOMINANT; MALE
DOMINATED; MASCULINE; MASCULINITY; MIS GENDER; MISGENDER; MISOGYNISTIC; MISOGYNY; NON BINARY;
NON BINARY GENDER; NON CONFORMING GENDER; NONBINARY; NONBINARY GENDER; NONCONFORMING
GENDER; OPPRESSED GENDER; OPPRESSED GENDERS; OPPRESSED SEXUALITIES; PANSEXUAL; PREDOMINATELY
MALE; PREFERRED GENDER; PREFERRED IDENTITY; PREFERRED SEX; PRIMARILY MALE; PRONOUN; PRONOUNS;
QUEER THEORY; SELF IDENTIFY; SEX CHANGE; SEX PREFERENCE; SEX TRANSITION; SEXISM; SEXIST; SEXUAL
DISCRIMINATION; SEXUAL DISPARITIES; SEXUAL DISPARITY; SEXUAL IDENTITY; SEXUAL MINORITIES; SEXUAL
MINORITY; SEXUAL PREFERENCE; SEXUAL PREFERENCES; SEXUALITIES; SEXUALITY; STRAIGHT WHITE; TOXIC
MASCULINITY; TRANSGENDER; TRANSGENDERISM; TRANSITIONING GENDER; TRANSITIONING SEX; TRANSJUSTICE;
TRANSPHOBIA; TRANSPHOBIC; UNDERREPRESENTED GENDER; VOICES OF WOMEN; WHITE FEMALE; WHITE
FEMALES; WHITE MALE; WHITE MALES; WHITE MEN; WHITE WOMEN; WOMEN; WOMEN AND GENDER;
WOMEN AND UNDERREPRESENTED; WOMENUNDERREPRESENTED
'''
racebanstring='''
ANTI BLACK; ANTI BLACK RACISM; ANTI RACISM; ANTI RACIST; ANTI WHITE; ANTIBLACK; ANTIBLACK RACISM;
ANTIRACISM; ANTIRACIST; ANTIWHITE; BIPOC; BIPOCX; BLACK AND LATINX; BLACK COMMUNITIES; BLACK
COMMUNITY; BLACK INDIGENOUS AND LATINX; BLACK INDIGENOUS AND OTHER; BLACK INDIGENOUS LATINX;
BLACK INDIGENOUS OTHER; BLACK INDIVIDUAL; BLACK INDIVIDUALS; BLACK INTELLECTUALISM; BLACK LIVES
MATTER; BLACK MINORITIES; BLACK MINORITY; BLACK PEOPLE; BLACK PERSON; BLACK THOUGHT; BLACK
VOICES; BLACKNESS; COLORED COMMUNITIES; COLORED COMMUNITY; COLORED INDIVIDUAL; COLORED
INDIVIDUALS; COLORED MINORITIES; COLORED MINORITY; COLORED PEOPLE; COLORED PERSON; COLORED
VOICES; CRITICAL RACE THEORY; ETHNIC AND RACIAL; ETHNIC BIAS; ETHNIC COMMUNITIES; ETHNIC
COMMUNITY; ETHNIC IDENTITIES; ETHNIC IDENTITY; ETHNIC INDIVIDUAL; ETHNIC INDIVIDUALS; ETHNIC
MINORITIES; ETHNIC MINORITY; ETHNIC PEOPLE; ETHNIC PERSON; ETHNIC RACISM; ETHNIC SEGREGATION;
ETHNIC VOICES; ETHNICAL RACISM; ETHNICITIES AND RACES; ETHNICITY; ETHNICITY AND RACE; HISPANIC
COMMUNITIES; HISPANIC COMMUNITY; HISPANIC INDIVIDUAL; HISPANIC INDIVIDUALS; HISPANIC MINORITIES;
HISPANIC MINORITY; HISPANIC PEOPLE; HISPANIC PERSON; HISPANIC VOICES; HISTORICAL RACISM;
HISTORICALLY RACIST; HISTORICALLY WHITE; INDIGENOUS COMMUNITIES; INDIGENOUS COMMUNITY;
INDIGENOUS INDIVIDUAL; INDIGENOUS INDIVIDUALS; INDIGENOUS MINORITIES; INDIGENOUS MINORITY;
INDIGENOUS PEOPLE; INDIGENOUS PERSON; INDIGENOUS VOICES; INSTITUTIONAL RACISM; INSTITUTIONALIZED
RACISM; INSTITUTIONALLY RACIST; INTER RACIAL; INTER RACIALLY; INTERRACIAL; INTERRACIALLY; LATINA
COMMUNITIES; LATINA COMMUNITY; LATINA INDIVIDUAL; LATINA INDIVIDUALS; LATINA MINORITIES; LATINA
MINORITY; LATINA PEOPLE; LATINA PERSON; LATINA VOICES; LATINX COMMUNITIES; LATINX COMMUNITY;
LATINX INDIVIDUAL; LATINX INDIVIDUALS; LATINX MINORITIES; LATINX MINORITY; LATINX PEOPLE; LATINX
PERSON; LATINX VOICES; MULTI ETHNIC; MULTI ETHNICALLY; MULTIETHNIC; MULTIETHNICALLY; NON BLACK;
NON WHITE; NONBLACK; NONWHITE; PEOPLE OF COLOR; POC; POCX; PREDOMINATELY WHITE; PRIMARILY
WHITE; PRIVILEGED WHITE; PRO BLACK; PRO WHITE; PROBLACK; PROWHITE; RACE AND CULTURE; RACE AND
ETHNICITY; RACE BASED; RACEBASED; RACES AND CULTURES; RACES AND ETHNICITIES; RACIAL; RACIAL AND
CULTURAL; RACIAL AND ETHNIC; RACIAL BIAS; RACIAL BIASES; RACIAL DISPARITIES; RACIAL DISPARITY; RACIAL
DIVERSITY; RACIAL IDENTITY; RACIAL INEQUALITIES; RACIAL INEQUALITY; RACIAL INEQUITIES; RACIAL INEQUITY;
RACIAL INJUSTICE; RACIAL INJUSTICES; RACIAL JUSTICE; RACIAL MINORITIES; RACIAL MINORITY; RACIAL
OPPRESSION; RACIAL PREJUDICE; RACIAL PREJUDICES; RACIAL SEGREGATION; RACIAL SOCIALIZATION; RACIAL
SOLIDARITY; RACIAL STEREOTYPES; RACIAL VIOLENCE; RACIALLY; RACIALLY AND CULTURALLY; RACIALLY BIAS;
RACIALLY BIASED; RACIALLY OPPRESSED; RACISM; RACIST; SEGREGATED ETHNICITIES; SEGREGATED ETHNICITY;
SEGREGATED RACE; SEGREGATED RACES; STRUCTURAL RACISM; STRUCTURALLY RACIST; SYSTEMIC RACISM;
SYSTEMICALLY RACIST; TOKENISTIC; TOKENSIM; TRANS ETHNIC; TRANSETHNIC; WHITE COLONIALISM; WHITE
COLONIZATION; WHITE COLONIZER; WHITE COLONIZERS; WHITE FRAGILITY; WHITE HISTORICALLY; WHITE
NATIONALISM; WHITE NATIONALIST; WHITE PEOPLE; WHITE PERSON; WHITE PRIVILEGE; WHITE SERVING; WHITE
SUPREMACY; WHITENESS.
'''

environmentaljusticebanstring='''
CLIMATE ACTION; CLIMATE CONSCIOUS; CLIMATE CONSCIOUSNESS; CLIMATE EQUALITY; CLIMATE EQUITY;
CLIMATE JUSTICE; CLIMATE RESEARCH; ECO CULTURAL; ECOCULTURAL; ENVIRONMENT CONSCIOUS;
ENVIRONMENT CONSCIOUSNESS; ENVIRONMENTAL CONSCIOUS; ENVIRONMENTAL CONSCIOUSNESS;
ENVIRONMENTAL EQUALITY; ENVIRONMENTAL EQUITY; ENVIRONMENTAL GOVERNANCE; ENVIRONMENTAL JUSTICE;
ENVIRONMENTAL SOCIAL; ENVIRONMENTALGOVERNANCE; ENVIRONMENTALLY CONSCIOUS;
ENVIRONMENTALSOCIAL; ESG; ESG EFFORT; ESG EFFORTS; ESG INITIATIVE; ESG INITIATIVES; GREEN NEW
DEAL; NET ZERO; NETZERO; SOCIAL ENVIRONMENTAL; SOCIALENVIRONMENTAL; CLIMATE INJUSTICE; CLIMATE
JUSTICES; CLIMATE INJUSTICES; CLIMATE CHANGE; GREEN INFRASTRUCTURE; GREEN SOCIETY; CLEAN ENERGY.
'''